// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bmardale/skjul/internal/db/sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=internal/db/sqlc/sqlctest/mock_querier.go -package=sqlctest github.com/bmardale/skjul/internal/db/sqlc Querier
//

// Package sqlctest is a generated GoMock package.
package sqlctest

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/bmardale/skjul/internal/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountAttachmentsByNoteID mocks base method.
func (m *MockQuerier) CountAttachmentsByNoteID(ctx context.Context, noteID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAttachmentsByNoteID", ctx, noteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAttachmentsByNoteID indicates an expected call of CountAttachmentsByNoteID.
func (mr *MockQuerierMockRecorder) CountAttachmentsByNoteID(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAttachmentsByNoteID", reflect.TypeOf((*MockQuerier)(nil).CountAttachmentsByNoteID), ctx, noteID)
}

// CountInvitationsByCreator mocks base method.
func (m *MockQuerier) CountInvitationsByCreator(ctx context.Context, createdBy uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInvitationsByCreator", ctx, createdBy)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInvitationsByCreator indicates an expected call of CountInvitationsByCreator.
func (mr *MockQuerierMockRecorder) CountInvitationsByCreator(ctx, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInvitationsByCreator", reflect.TypeOf((*MockQuerier)(nil).CountInvitationsByCreator), ctx, createdBy)
}

// CreateAttachment mocks base method.
func (m *MockQuerier) CreateAttachment(ctx context.Context, arg sqlc.CreateAttachmentParams) (sqlc.CreateAttachmentRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttachment", ctx, arg)
	ret0, _ := ret[0].(sqlc.CreateAttachmentRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachment indicates an expected call of CreateAttachment.
func (mr *MockQuerierMockRecorder) CreateAttachment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachment", reflect.TypeOf((*MockQuerier)(nil).CreateAttachment), ctx, arg)
}

// CreateInvitation mocks base method.
func (m *MockQuerier) CreateInvitation(ctx context.Context, arg sqlc.CreateInvitationParams) (sqlc.CreateInvitationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, arg)
	ret0, _ := ret[0].(sqlc.CreateInvitationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockQuerierMockRecorder) CreateInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockQuerier)(nil).CreateInvitation), ctx, arg)
}

// CreateNote mocks base method.
func (m *MockQuerier) CreateNote(ctx context.Context, arg sqlc.CreateNoteParams) (sqlc.CreateNoteRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, arg)
	ret0, _ := ret[0].(sqlc.CreateNoteRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockQuerierMockRecorder) CreateNote(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockQuerier)(nil).CreateNote), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockQuerier) CreateSession(ctx context.Context, arg sqlc.CreateSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockQuerierMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockQuerier)(nil).CreateSession), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// DeleteExpiredNotes mocks base method.
func (m *MockQuerier) DeleteExpiredNotes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredNotes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredNotes indicates an expected call of DeleteExpiredNotes.
func (mr *MockQuerierMockRecorder) DeleteExpiredNotes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredNotes", reflect.TypeOf((*MockQuerier)(nil).DeleteExpiredNotes), ctx)
}

// DeleteExpiredSessions mocks base method.
func (m *MockQuerier) DeleteExpiredSessions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredSessions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredSessions indicates an expected call of DeleteExpiredSessions.
func (mr *MockQuerierMockRecorder) DeleteExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredSessions", reflect.TypeOf((*MockQuerier)(nil).DeleteExpiredSessions), ctx)
}

// DeleteNoteByID mocks base method.
func (m *MockQuerier) DeleteNoteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNoteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNoteByID indicates an expected call of DeleteNoteByID.
func (mr *MockQuerierMockRecorder) DeleteNoteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNoteByID", reflect.TypeOf((*MockQuerier)(nil).DeleteNoteByID), ctx, id)
}

// DeleteNoteByIDAndUserID mocks base method.
func (m *MockQuerier) DeleteNoteByIDAndUserID(ctx context.Context, arg sqlc.DeleteNoteByIDAndUserIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNoteByIDAndUserID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNoteByIDAndUserID indicates an expected call of DeleteNoteByIDAndUserID.
func (mr *MockQuerierMockRecorder) DeleteNoteByIDAndUserID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNoteByIDAndUserID", reflect.TypeOf((*MockQuerier)(nil).DeleteNoteByIDAndUserID), ctx, arg)
}

// DeleteSession mocks base method.
func (m *MockQuerier) DeleteSession(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockQuerierMockRecorder) DeleteSession(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockQuerier)(nil).DeleteSession), ctx, tokenHash)
}

// DeleteSessionByID mocks base method.
func (m *MockQuerier) DeleteSessionByID(ctx context.Context, arg sqlc.DeleteSessionByIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionByID indicates an expected call of DeleteSessionByID.
func (mr *MockQuerierMockRecorder) DeleteSessionByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByID", reflect.TypeOf((*MockQuerier)(nil).DeleteSessionByID), ctx, arg)
}

// DeleteUser mocks base method.
func (m *MockQuerier) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockQuerierMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockQuerier)(nil).DeleteUser), ctx, id)
}

// GetAttachmentS3KeysByNoteID mocks base method.
func (m *MockQuerier) GetAttachmentS3KeysByNoteID(ctx context.Context, noteID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentS3KeysByNoteID", ctx, noteID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentS3KeysByNoteID indicates an expected call of GetAttachmentS3KeysByNoteID.
func (mr *MockQuerierMockRecorder) GetAttachmentS3KeysByNoteID(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentS3KeysByNoteID", reflect.TypeOf((*MockQuerier)(nil).GetAttachmentS3KeysByNoteID), ctx, noteID)
}

// GetAttachmentS3KeysForExpiredNotes mocks base method.
func (m *MockQuerier) GetAttachmentS3KeysForExpiredNotes(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentS3KeysForExpiredNotes", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentS3KeysForExpiredNotes indicates an expected call of GetAttachmentS3KeysForExpiredNotes.
func (mr *MockQuerierMockRecorder) GetAttachmentS3KeysForExpiredNotes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentS3KeysForExpiredNotes", reflect.TypeOf((*MockQuerier)(nil).GetAttachmentS3KeysForExpiredNotes), ctx)
}

// GetInvitationByCode mocks base method.
func (m *MockQuerier) GetInvitationByCode(ctx context.Context, code string) (sqlc.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitationByCode", ctx, code)
	ret0, _ := ret[0].(sqlc.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitationByCode indicates an expected call of GetInvitationByCode.
func (mr *MockQuerierMockRecorder) GetInvitationByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitationByCode", reflect.TypeOf((*MockQuerier)(nil).GetInvitationByCode), ctx, code)
}

// GetLoginChallengeByUsername mocks base method.
func (m *MockQuerier) GetLoginChallengeByUsername(ctx context.Context, username string) (sqlc.GetLoginChallengeByUsernameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginChallengeByUsername", ctx, username)
	ret0, _ := ret[0].(sqlc.GetLoginChallengeByUsernameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginChallengeByUsername indicates an expected call of GetLoginChallengeByUsername.
func (mr *MockQuerierMockRecorder) GetLoginChallengeByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginChallengeByUsername", reflect.TypeOf((*MockQuerier)(nil).GetLoginChallengeByUsername), ctx, username)
}

// GetNoteByID mocks base method.
func (m *MockQuerier) GetNoteByID(ctx context.Context, id uuid.UUID) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByID indicates an expected call of GetNoteByID.
func (mr *MockQuerierMockRecorder) GetNoteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByID", reflect.TypeOf((*MockQuerier)(nil).GetNoteByID), ctx, id)
}

// GetNoteMetaByID mocks base method.
func (m *MockQuerier) GetNoteMetaByID(ctx context.Context, id uuid.UUID) (sqlc.GetNoteMetaByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteMetaByID", ctx, id)
	ret0, _ := ret[0].(sqlc.GetNoteMetaByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteMetaByID indicates an expected call of GetNoteMetaByID.
func (mr *MockQuerierMockRecorder) GetNoteMetaByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteMetaByID", reflect.TypeOf((*MockQuerier)(nil).GetNoteMetaByID), ctx, id)
}

// GetNoteUserID mocks base method.
func (m *MockQuerier) GetNoteUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteUserID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteUserID indicates an expected call of GetNoteUserID.
func (mr *MockQuerierMockRecorder) GetNoteUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteUserID", reflect.TypeOf((*MockQuerier)(nil).GetNoteUserID), ctx, id)
}

// GetSessionByToken mocks base method.
func (m *MockQuerier) GetSessionByToken(ctx context.Context, tokenHash string) (sqlc.GetSessionByTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByToken", ctx, tokenHash)
	ret0, _ := ret[0].(sqlc.GetSessionByTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByToken indicates an expected call of GetSessionByToken.
func (mr *MockQuerierMockRecorder) GetSessionByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByToken", reflect.TypeOf((*MockQuerier)(nil).GetSessionByToken), ctx, tokenHash)
}

// GetSessionByUserId mocks base method.
func (m *MockQuerier) GetSessionByUserId(ctx context.Context, userID uuid.UUID) (sqlc.GetSessionByUserIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByUserId", ctx, userID)
	ret0, _ := ret[0].(sqlc.GetSessionByUserIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByUserId indicates an expected call of GetSessionByUserId.
func (mr *MockQuerierMockRecorder) GetSessionByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByUserId", reflect.TypeOf((*MockQuerier)(nil).GetSessionByUserId), ctx, userID)
}

// GetUser mocks base method.
func (m *MockQuerier) GetUser(ctx context.Context, id uuid.UUID) (sqlc.GetUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(sqlc.GetUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockQuerierMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockQuerier)(nil).GetUser), ctx, id)
}

// GetUserBasic mocks base method.
func (m *MockQuerier) GetUserBasic(ctx context.Context, id uuid.UUID) (sqlc.GetUserBasicRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBasic", ctx, id)
	ret0, _ := ret[0].(sqlc.GetUserBasicRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBasic indicates an expected call of GetUserBasic.
func (mr *MockQuerierMockRecorder) GetUserBasic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBasic", reflect.TypeOf((*MockQuerier)(nil).GetUserBasic), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockQuerier) GetUserByUsername(ctx context.Context, username string) (sqlc.GetUserByUsernameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(sqlc.GetUserByUsernameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockQuerierMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockQuerier)(nil).GetUserByUsername), ctx, username)
}

// GetUserInviteQuota mocks base method.
func (m *MockQuerier) GetUserInviteQuota(ctx context.Context, id uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInviteQuota", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInviteQuota indicates an expected call of GetUserInviteQuota.
func (mr *MockQuerierMockRecorder) GetUserInviteQuota(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInviteQuota", reflect.TypeOf((*MockQuerier)(nil).GetUserInviteQuota), ctx, id)
}

// GetUserStats mocks base method.
func (m *MockQuerier) GetUserStats(ctx context.Context, userID uuid.UUID) (sqlc.GetUserStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStats", ctx, userID)
	ret0, _ := ret[0].(sqlc.GetUserStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockQuerierMockRecorder) GetUserStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockQuerier)(nil).GetUserStats), ctx, userID)
}

// GetValidSessionByToken mocks base method.
func (m *MockQuerier) GetValidSessionByToken(ctx context.Context, tokenHash string) (sqlc.GetValidSessionByTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidSessionByToken", ctx, tokenHash)
	ret0, _ := ret[0].(sqlc.GetValidSessionByTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidSessionByToken indicates an expected call of GetValidSessionByToken.
func (mr *MockQuerierMockRecorder) GetValidSessionByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidSessionByToken", reflect.TypeOf((*MockQuerier)(nil).GetValidSessionByToken), ctx, tokenHash)
}

// ListAllUsers mocks base method.
func (m *MockQuerier) ListAllUsers(ctx context.Context) ([]sqlc.ListAllUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUsers", ctx)
	ret0, _ := ret[0].([]sqlc.ListAllUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUsers indicates an expected call of ListAllUsers.
func (mr *MockQuerierMockRecorder) ListAllUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUsers", reflect.TypeOf((*MockQuerier)(nil).ListAllUsers), ctx)
}

// ListAttachmentsByNoteID mocks base method.
func (m *MockQuerier) ListAttachmentsByNoteID(ctx context.Context, noteID uuid.UUID) ([]sqlc.ListAttachmentsByNoteIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttachmentsByNoteID", ctx, noteID)
	ret0, _ := ret[0].([]sqlc.ListAttachmentsByNoteIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachmentsByNoteID indicates an expected call of ListAttachmentsByNoteID.
func (mr *MockQuerierMockRecorder) ListAttachmentsByNoteID(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachmentsByNoteID", reflect.TypeOf((*MockQuerier)(nil).ListAttachmentsByNoteID), ctx, noteID)
}

// ListInvitationsByCreator mocks base method.
func (m *MockQuerier) ListInvitationsByCreator(ctx context.Context, createdBy uuid.UUID) ([]sqlc.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitationsByCreator", ctx, createdBy)
	ret0, _ := ret[0].([]sqlc.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitationsByCreator indicates an expected call of ListInvitationsByCreator.
func (mr *MockQuerierMockRecorder) ListInvitationsByCreator(ctx, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitationsByCreator", reflect.TypeOf((*MockQuerier)(nil).ListInvitationsByCreator), ctx, createdBy)
}

// ListNotesByUserID mocks base method.
func (m *MockQuerier) ListNotesByUserID(ctx context.Context, userID uuid.UUID) ([]sqlc.ListNotesByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotesByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.ListNotesByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotesByUserID indicates an expected call of ListNotesByUserID.
func (mr *MockQuerierMockRecorder) ListNotesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotesByUserID", reflect.TypeOf((*MockQuerier)(nil).ListNotesByUserID), ctx, userID)
}

// ListNotesByUserIDPaginated mocks base method.
func (m *MockQuerier) ListNotesByUserIDPaginated(ctx context.Context, arg sqlc.ListNotesByUserIDPaginatedParams) ([]sqlc.ListNotesByUserIDPaginatedRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotesByUserIDPaginated", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListNotesByUserIDPaginatedRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotesByUserIDPaginated indicates an expected call of ListNotesByUserIDPaginated.
func (mr *MockQuerierMockRecorder) ListNotesByUserIDPaginated(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotesByUserIDPaginated", reflect.TypeOf((*MockQuerier)(nil).ListNotesByUserIDPaginated), ctx, arg)
}

// ListSessionsByUserID mocks base method.
func (m *MockQuerier) ListSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]sqlc.ListSessionsByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.ListSessionsByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByUserID indicates an expected call of ListSessionsByUserID.
func (mr *MockQuerierMockRecorder) ListSessionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByUserID", reflect.TypeOf((*MockQuerier)(nil).ListSessionsByUserID), ctx, userID)
}

// RedeemInvitation mocks base method.
func (m *MockQuerier) RedeemInvitation(ctx context.Context, arg sqlc.RedeemInvitationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemInvitation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedeemInvitation indicates an expected call of RedeemInvitation.
func (mr *MockQuerierMockRecorder) RedeemInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemInvitation", reflect.TypeOf((*MockQuerier)(nil).RedeemInvitation), ctx, arg)
}

// UpdateSessionTokenHash mocks base method.
func (m *MockQuerier) UpdateSessionTokenHash(ctx context.Context, arg sqlc.UpdateSessionTokenHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionTokenHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionTokenHash indicates an expected call of UpdateSessionTokenHash.
func (mr *MockQuerierMockRecorder) UpdateSessionTokenHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionTokenHash", reflect.TypeOf((*MockQuerier)(nil).UpdateSessionTokenHash), ctx, arg)
}

// UpdateUserInviteQuota mocks base method.
func (m *MockQuerier) UpdateUserInviteQuota(ctx context.Context, arg sqlc.UpdateUserInviteQuotaParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserInviteQuota", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserInviteQuota indicates an expected call of UpdateUserInviteQuota.
func (mr *MockQuerierMockRecorder) UpdateUserInviteQuota(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserInviteQuota", reflect.TypeOf((*MockQuerier)(nil).UpdateUserInviteQuota), ctx, arg)
}
