// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachment.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAttachmentsByNoteID = `-- name: CountAttachmentsByNoteID :one
SELECT count(*) FROM attachments WHERE note_id = $1
`

func (q *Queries) CountAttachmentsByNoteID(ctx context.Context, noteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByNoteID, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, note_id, s3_key, encrypted_size, filename_ciphertext, filename_nonce, content_nonce, mime_ciphertext, mime_nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type CreateAttachmentParams struct {
	ID                 uuid.UUID
	NoteID             uuid.UUID
	S3Key              string
	EncryptedSize      int64
	FilenameCiphertext []byte
	FilenameNonce      []byte
	ContentNonce       []byte
	MimeCiphertext     []byte
	MimeNonce          []byte
}

type CreateAttachmentRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.NoteID,
		arg.S3Key,
		arg.EncryptedSize,
		arg.FilenameCiphertext,
		arg.FilenameNonce,
		arg.ContentNonce,
		arg.MimeCiphertext,
		arg.MimeNonce,
	)
	var i CreateAttachmentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getAttachmentS3KeysByNoteID = `-- name: GetAttachmentS3KeysByNoteID :many
SELECT s3_key FROM attachments WHERE note_id = $1
`

func (q *Queries) GetAttachmentS3KeysByNoteID(ctx context.Context, noteID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getAttachmentS3KeysByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var s3_key string
		if err := rows.Scan(&s3_key); err != nil {
			return nil, err
		}
		items = append(items, s3_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachmentS3KeysForExpiredNotes = `-- name: GetAttachmentS3KeysForExpiredNotes :many
SELECT s3_key FROM attachments
WHERE note_id IN (SELECT id FROM notes WHERE expires_at <= now())
`

func (q *Queries) GetAttachmentS3KeysForExpiredNotes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAttachmentS3KeysForExpiredNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var s3_key string
		if err := rows.Scan(&s3_key); err != nil {
			return nil, err
		}
		items = append(items, s3_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByNoteID = `-- name: ListAttachmentsByNoteID :many
SELECT id, s3_key, encrypted_size, filename_ciphertext, filename_nonce, content_nonce, mime_ciphertext, mime_nonce, created_at
FROM attachments
WHERE note_id = $1
ORDER BY created_at
`

type ListAttachmentsByNoteIDRow struct {
	ID                 uuid.UUID
	S3Key              string
	EncryptedSize      int64
	FilenameCiphertext []byte
	FilenameNonce      []byte
	ContentNonce       []byte
	MimeCiphertext     []byte
	MimeNonce          []byte
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) ListAttachmentsByNoteID(ctx context.Context, noteID uuid.UUID) ([]ListAttachmentsByNoteIDRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByNoteIDRow
	for rows.Next() {
		var i ListAttachmentsByNoteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.S3Key,
			&i.EncryptedSize,
			&i.FilenameCiphertext,
			&i.FilenameNonce,
			&i.ContentNonce,
			&i.MimeCiphertext,
			&i.MimeNonce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
