// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvitationsByCreator = `-- name: CountInvitationsByCreator :one
SELECT count(*) FROM invitations WHERE created_by = $1
`

func (q *Queries) CountInvitationsByCreator(ctx context.Context, createdBy uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitationsByCreator, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (code, created_by)
VALUES ($1, $2)
RETURNING id, code, created_by, created_at
`

type CreateInvitationParams struct {
	Code      string
	CreatedBy uuid.UUID
}

type CreateInvitationRow struct {
	ID        uuid.UUID
	Code      string
	CreatedBy uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation, arg.Code, arg.CreatedBy)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByCode = `-- name: GetInvitationByCode :one
SELECT id, code, created_by, used_by, created_at, used_at
FROM invitations
WHERE code = $1 AND used_by IS NULL
`

func (q *Queries) GetInvitationByCode(ctx context.Context, code string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByCode, code)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const listInvitationsByCreator = `-- name: ListInvitationsByCreator :many
SELECT id, code, created_by, used_by, created_at, used_at
FROM invitations
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByCreator(ctx context.Context, createdBy uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedBy,
			&i.UsedBy,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvitation = `-- name: RedeemInvitation :exec
UPDATE invitations
SET used_by = $2, used_at = now()
WHERE code = $1
`

type RedeemInvitationParams struct {
	Code   string
	UsedBy pgtype.UUID
}

func (q *Queries) RedeemInvitation(ctx context.Context, arg RedeemInvitationParams) error {
	_, err := q.db.Exec(ctx, redeemInvitation, arg.Code, arg.UsedBy)
	return err
}
