// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	BurnAfterRead     bool
	TitleCiphertext   []byte
	TitleNonce        []byte
	BodyCiphertext    []byte
	BodyNonce         []byte
	EncryptedKey      []byte
	EncryptedKeyNonce []byte
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                uuid.UUID
	Username          string
	AuthHash          string
	Salt              []byte
	EncryptedVaultKey []byte
	VaultKeyNonce     []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
