// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paste.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  user_id,
  burn_after_read,
  title_ciphertext, title_nonce,
  body_ciphertext, body_nonce,
  encrypted_key, encrypted_key_nonce,
  expires_at
) VALUES (
  $1, $2,
  $3, $4,
  $5, $6,
  $7, $8,
  $9
)
RETURNING id, created_at, expires_at
`

type CreateNoteParams struct {
	UserID            uuid.UUID
	BurnAfterRead     bool
	TitleCiphertext   []byte
	TitleNonce        []byte
	BodyCiphertext    []byte
	BodyNonce         []byte
	EncryptedKey      []byte
	EncryptedKeyNonce []byte
	ExpiresAt         pgtype.Timestamptz
}

type CreateNoteRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.BurnAfterRead,
		arg.TitleCiphertext,
		arg.TitleNonce,
		arg.BodyCiphertext,
		arg.BodyNonce,
		arg.EncryptedKey,
		arg.EncryptedKeyNonce,
		arg.ExpiresAt,
	)
	var i CreateNoteRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const deleteExpiredNotes = `-- name: DeleteExpiredNotes :exec
DELETE FROM notes
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredNotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNotes)
	return err
}

const deleteNoteByID = `-- name: DeleteNoteByID :exec
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNoteByID, id)
	return err
}

const deleteNoteByIDAndUserID = `-- name: DeleteNoteByIDAndUserID :exec
DELETE FROM notes
WHERE id = $1
  AND user_id = $2
`

type DeleteNoteByIDAndUserIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNoteByIDAndUserID(ctx context.Context, arg DeleteNoteByIDAndUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteNoteByIDAndUserID, arg.ID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT
  id, user_id, burn_after_read,
  title_ciphertext, title_nonce,
  body_ciphertext, body_nonce,
  encrypted_key, encrypted_key_nonce,
  created_at, expires_at
FROM notes
WHERE id = $1
  AND expires_at > now()
`

func (q *Queries) GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BurnAfterRead,
		&i.TitleCiphertext,
		&i.TitleNonce,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.EncryptedKey,
		&i.EncryptedKeyNonce,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listNotesByUserID = `-- name: ListNotesByUserID :many
SELECT
  id,
  burn_after_read,
  title_ciphertext, title_nonce,
  encrypted_key, encrypted_key_nonce,
  created_at,
  expires_at
FROM notes
WHERE user_id = $1
  AND expires_at > now()
ORDER BY created_at DESC
`

type ListNotesByUserIDRow struct {
	ID                uuid.UUID
	BurnAfterRead     bool
	TitleCiphertext   []byte
	TitleNonce        []byte
	EncryptedKey      []byte
	EncryptedKeyNonce []byte
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) ListNotesByUserID(ctx context.Context, userID uuid.UUID) ([]ListNotesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listNotesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesByUserIDRow
	for rows.Next() {
		var i ListNotesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BurnAfterRead,
			&i.TitleCiphertext,
			&i.TitleNonce,
			&i.EncryptedKey,
			&i.EncryptedKeyNonce,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
