// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paste.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  user_id,
  burn_after_read,
  title_ciphertext, title_nonce,
  body_ciphertext, body_nonce,
  encrypted_key, encrypted_key_nonce,
  expires_at,
  language_id
) VALUES (
  $1, $2,
  $3, $4,
  $5, $6,
  $7, $8,
  $9, $10
)
RETURNING id, created_at, expires_at
`

type CreateNoteParams struct {
	UserID            uuid.UUID
	BurnAfterRead     bool
	TitleCiphertext   []byte
	TitleNonce        []byte
	BodyCiphertext    []byte
	BodyNonce         []byte
	EncryptedKey      []byte
	EncryptedKeyNonce []byte
	ExpiresAt         pgtype.Timestamptz
	LanguageID        pgtype.Text
}

type CreateNoteRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.BurnAfterRead,
		arg.TitleCiphertext,
		arg.TitleNonce,
		arg.BodyCiphertext,
		arg.BodyNonce,
		arg.EncryptedKey,
		arg.EncryptedKeyNonce,
		arg.ExpiresAt,
		arg.LanguageID,
	)
	var i CreateNoteRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const deleteExpiredNotes = `-- name: DeleteExpiredNotes :exec
DELETE FROM notes
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredNotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNotes)
	return err
}

const deleteNoteByID = `-- name: DeleteNoteByID :exec
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNoteByID, id)
	return err
}

const deleteNoteByIDAndUserID = `-- name: DeleteNoteByIDAndUserID :exec
DELETE FROM notes
WHERE id = $1
  AND user_id = $2
`

type DeleteNoteByIDAndUserIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNoteByIDAndUserID(ctx context.Context, arg DeleteNoteByIDAndUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteNoteByIDAndUserID, arg.ID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT
  id, user_id, burn_after_read,
  title_ciphertext, title_nonce,
  body_ciphertext, body_nonce,
  encrypted_key, encrypted_key_nonce,
  created_at, expires_at,
  language_id
FROM notes
WHERE id = $1
  AND expires_at > now()
`

func (q *Queries) GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BurnAfterRead,
		&i.TitleCiphertext,
		&i.TitleNonce,
		&i.BodyCiphertext,
		&i.BodyNonce,
		&i.EncryptedKey,
		&i.EncryptedKeyNonce,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LanguageID,
	)
	return i, err
}

const getNoteUserID = `-- name: GetNoteUserID :one
SELECT user_id FROM notes WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetNoteUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getNoteUserID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listNotesByUserID = `-- name: ListNotesByUserID :many
SELECT
  n.id,
  n.burn_after_read,
  n.title_ciphertext, n.title_nonce,
  n.encrypted_key, n.encrypted_key_nonce,
  n.created_at,
  n.expires_at,
  n.language_id,
  coalesce(a.attachment_count, 0)::bigint as attachment_count
FROM notes n
LEFT JOIN (
  SELECT note_id, count(*)::bigint as attachment_count
  FROM attachments
  GROUP BY note_id
) a ON n.id = a.note_id
WHERE n.user_id = $1
  AND n.expires_at > now()
ORDER BY n.created_at DESC
`

type ListNotesByUserIDRow struct {
	ID                uuid.UUID
	BurnAfterRead     bool
	TitleCiphertext   []byte
	TitleNonce        []byte
	EncryptedKey      []byte
	EncryptedKeyNonce []byte
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	LanguageID        pgtype.Text
	AttachmentCount   int64
}

func (q *Queries) ListNotesByUserID(ctx context.Context, userID uuid.UUID) ([]ListNotesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listNotesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesByUserIDRow
	for rows.Next() {
		var i ListNotesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BurnAfterRead,
			&i.TitleCiphertext,
			&i.TitleNonce,
			&i.EncryptedKey,
			&i.EncryptedKeyNonce,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LanguageID,
			&i.AttachmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByUserIDPaginated = `-- name: ListNotesByUserIDPaginated :many
SELECT
  n.id,
  n.burn_after_read,
  n.title_ciphertext, n.title_nonce,
  n.encrypted_key, n.encrypted_key_nonce,
  n.created_at,
  n.expires_at,
  n.language_id,
  coalesce(a.attachment_count, 0)::bigint as attachment_count
FROM notes n
LEFT JOIN (
  SELECT note_id, count(*)::bigint as attachment_count
  FROM attachments
  GROUP BY note_id
) a ON n.id = a.note_id
WHERE n.user_id = $1
  AND n.expires_at > now()
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR n.id < $2::uuid)
ORDER BY n.id DESC
LIMIT $3
`

type ListNotesByUserIDPaginatedParams struct {
	UserID  uuid.UUID
	Column2 uuid.UUID
	Limit   int32
}

type ListNotesByUserIDPaginatedRow struct {
	ID                uuid.UUID
	BurnAfterRead     bool
	TitleCiphertext   []byte
	TitleNonce        []byte
	EncryptedKey      []byte
	EncryptedKeyNonce []byte
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	LanguageID        pgtype.Text
	AttachmentCount   int64
}

func (q *Queries) ListNotesByUserIDPaginated(ctx context.Context, arg ListNotesByUserIDPaginatedParams) ([]ListNotesByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listNotesByUserIDPaginated, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesByUserIDPaginatedRow
	for rows.Next() {
		var i ListNotesByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.BurnAfterRead,
			&i.TitleCiphertext,
			&i.TitleNonce,
			&i.EncryptedKey,
			&i.EncryptedKeyNonce,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LanguageID,
			&i.AttachmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
