// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAttachmentsByNoteID(ctx context.Context, noteID uuid.UUID) (int64, error)
	CountInvitationsByCreator(ctx context.Context, createdBy uuid.UUID) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteExpiredNotes(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteNoteByID(ctx context.Context, id uuid.UUID) error
	DeleteNoteByIDAndUserID(ctx context.Context, arg DeleteNoteByIDAndUserIDParams) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAttachmentS3KeysByNoteID(ctx context.Context, noteID uuid.UUID) ([]string, error)
	GetAttachmentS3KeysForExpiredNotes(ctx context.Context) ([]string, error)
	GetInvitationByCode(ctx context.Context, code string) (Invitation, error)
	GetLoginChallengeByUsername(ctx context.Context, username string) (GetLoginChallengeByUsernameRow, error)
	GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error)
	GetNoteMetaByID(ctx context.Context, id uuid.UUID) (GetNoteMetaByIDRow, error)
	GetNoteUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetSessionByToken(ctx context.Context, tokenHash string) (GetSessionByTokenRow, error)
	GetSessionByUserId(ctx context.Context, userID uuid.UUID) (GetSessionByUserIdRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error)
	GetUserBasic(ctx context.Context, id uuid.UUID) (GetUserBasicRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserInviteQuota(ctx context.Context, id uuid.UUID) (int32, error)
	GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error)
	GetValidSessionByToken(ctx context.Context, tokenHash string) (GetValidSessionByTokenRow, error)
	ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error)
	ListAttachmentsByNoteID(ctx context.Context, noteID uuid.UUID) ([]ListAttachmentsByNoteIDRow, error)
	ListInvitationsByCreator(ctx context.Context, createdBy uuid.UUID) ([]Invitation, error)
	ListNotesByUserID(ctx context.Context, userID uuid.UUID) ([]ListNotesByUserIDRow, error)
	ListNotesByUserIDPaginated(ctx context.Context, arg ListNotesByUserIDPaginatedParams) ([]ListNotesByUserIDPaginatedRow, error)
	ListSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]ListSessionsByUserIDRow, error)
	RedeemInvitation(ctx context.Context, arg RedeemInvitationParams) error
	UpdateSessionTokenHash(ctx context.Context, arg UpdateSessionTokenHashParams) error
	UpdateUserInviteQuota(ctx context.Context, arg UpdateUserInviteQuotaParams) error
}

var _ Querier = (*Queries)(nil)
