// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    user_id, token_hash, expires_at
) VALUES (
    $1, $2, $3
)
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token_hash FROM sessions WHERE token_hash = $1
`

type GetSessionByTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i GetSessionByTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.TokenHash)
	return i, err
}

const getSessionByUserId = `-- name: GetSessionByUserId :one
SELECT id, user_id, token_hash FROM sessions WHERE user_id = $1
`

type GetSessionByUserIdRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) GetSessionByUserId(ctx context.Context, userID uuid.UUID) (GetSessionByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getSessionByUserId, userID)
	var i GetSessionByUserIdRow
	err := row.Scan(&i.ID, &i.UserID, &i.TokenHash)
	return i, err
}

const getValidSessionByToken = `-- name: GetValidSessionByToken :one
SELECT id, user_id, token_hash FROM sessions WHERE token_hash = $1 AND expires_at > now()
`

type GetValidSessionByTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) GetValidSessionByToken(ctx context.Context, tokenHash string) (GetValidSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getValidSessionByToken, tokenHash)
	var i GetValidSessionByTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.TokenHash)
	return i, err
}

const updateSessionTokenHash = `-- name: UpdateSessionTokenHash :exec
UPDATE sessions SET token_hash = $1 WHERE id = $2
`

type UpdateSessionTokenHashParams struct {
	TokenHash string
	ID        uuid.UUID
}

func (q *Queries) UpdateSessionTokenHash(ctx context.Context, arg UpdateSessionTokenHashParams) error {
	_, err := q.db.Exec(ctx, updateSessionTokenHash, arg.TokenHash, arg.ID)
	return err
}
