// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, auth_hash, salt, encrypted_vault_key, vault_key_nonce
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id
`

type CreateUserParams struct {
	Username          string
	AuthHash          string
	Salt              []byte
	EncryptedVaultKey []byte
	VaultKeyNonce     []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.AuthHash,
		arg.Salt,
		arg.EncryptedVaultKey,
		arg.VaultKeyNonce,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getLoginChallengeByUsername = `-- name: GetLoginChallengeByUsername :one
SELECT salt, encrypted_vault_key, vault_key_nonce FROM users WHERE username = $1
`

type GetLoginChallengeByUsernameRow struct {
	Salt              []byte
	EncryptedVaultKey []byte
	VaultKeyNonce     []byte
}

func (q *Queries) GetLoginChallengeByUsername(ctx context.Context, username string) (GetLoginChallengeByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getLoginChallengeByUsername, username)
	var i GetLoginChallengeByUsernameRow
	err := row.Scan(&i.Salt, &i.EncryptedVaultKey, &i.VaultKeyNonce)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, salt, encrypted_vault_key, vault_key_nonce, created_at FROM users WHERE id = $1
`

type GetUserRow struct {
	ID                uuid.UUID
	Username          string
	Salt              []byte
	EncryptedVaultKey []byte
	VaultKeyNonce     []byte
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Salt,
		&i.EncryptedVaultKey,
		&i.VaultKeyNonce,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, auth_hash FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID       uuid.UUID
	Username string
	AuthHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.AuthHash)
	return i, err
}

const getUserInviteQuota = `-- name: GetUserInviteQuota :one
SELECT invite_quota FROM users WHERE id = $1
`

func (q *Queries) GetUserInviteQuota(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserInviteQuota, id)
	var invite_quota int32
	err := row.Scan(&invite_quota)
	return invite_quota, err
}
