// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bmardale/skjul/internal/pastes (interfaces: ObjectStorage)
//
// Generated by this command:
//
//	mockgen -destination=internal/pastes/mock_storage_test.go -package=pastes github.com/bmardale/skjul/internal/pastes ObjectStorage
//

// Package pastes is a generated GoMock package.
package pastes

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// DeleteObjects mocks base method.
func (m *MockObjectStorage) DeleteObjects(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockObjectStorageMockRecorder) DeleteObjects(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockObjectStorage)(nil).DeleteObjects), ctx, keys)
}

// GenerateDownloadURL mocks base method.
func (m *MockObjectStorage) GenerateDownloadURL(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDownloadURL", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDownloadURL indicates an expected call of GenerateDownloadURL.
func (mr *MockObjectStorageMockRecorder) GenerateDownloadURL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDownloadURL", reflect.TypeOf((*MockObjectStorage)(nil).GenerateDownloadURL), ctx, key)
}

// GenerateUploadURL mocks base method.
func (m *MockObjectStorage) GenerateUploadURL(ctx context.Context, key string, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUploadURL", ctx, key, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUploadURL indicates an expected call of GenerateUploadURL.
func (mr *MockObjectStorageMockRecorder) GenerateUploadURL(ctx, key, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUploadURL", reflect.TypeOf((*MockObjectStorage)(nil).GenerateUploadURL), ctx, key, size)
}

// GetPublicURL mocks base method.
func (m *MockObjectStorage) GetPublicURL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicURL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPublicURL indicates an expected call of GetPublicURL.
func (mr *MockObjectStorageMockRecorder) GetPublicURL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicURL", reflect.TypeOf((*MockObjectStorage)(nil).GetPublicURL), key)
}

// PresignDuration mocks base method.
func (m *MockObjectStorage) PresignDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// PresignDuration indicates an expected call of PresignDuration.
func (mr *MockObjectStorageMockRecorder) PresignDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignDuration", reflect.TypeOf((*MockObjectStorage)(nil).PresignDuration))
}
